# Generated by Django 2.1.5 on 2019-02-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('pic', models.ImageField(null=True, upload_to='profile')),
            ],
        ),
    ]
